/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MeasurementGuideRouteImport } from './routes/measurement-guide'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FabricGuideRouteImport } from './routes/fabric-guide'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementGuideRoute = MeasurementGuideRouteImport.update({
  id: '/measurement-guide',
  path: '/measurement-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricGuideRoute = FabricGuideRouteImport.update({
  id: '/fabric-guide',
  path: '/fabric-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collections': typeof CollectionsRoute
  '/consultation': typeof ConsultationRoute
  '/design': typeof DesignRoute
  '/fabric-guide': typeof FabricGuideRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/measurement-guide': typeof MeasurementGuideRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/api/generate': typeof ApiGenerateRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collections': typeof CollectionsRoute
  '/consultation': typeof ConsultationRoute
  '/design': typeof DesignRoute
  '/fabric-guide': typeof FabricGuideRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/measurement-guide': typeof MeasurementGuideRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/api/generate': typeof ApiGenerateRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collections': typeof CollectionsRoute
  '/consultation': typeof ConsultationRoute
  '/design': typeof DesignRoute
  '/fabric-guide': typeof FabricGuideRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/measurement-guide': typeof MeasurementGuideRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/api/generate': typeof ApiGenerateRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/collections'
    | '/consultation'
    | '/design'
    | '/fabric-guide'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/measurement-guide'
    | '/privacy'
    | '/quote'
    | '/api/generate'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/collections'
    | '/consultation'
    | '/design'
    | '/fabric-guide'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/measurement-guide'
    | '/privacy'
    | '/quote'
    | '/api/generate'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/collections'
    | '/consultation'
    | '/design'
    | '/fabric-guide'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/measurement-guide'
    | '/privacy'
    | '/quote'
    | '/api/generate'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CollectionsRoute: typeof CollectionsRoute
  ConsultationRoute: typeof ConsultationRoute
  DesignRoute: typeof DesignRoute
  FabricGuideRoute: typeof FabricGuideRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MeasurementGuideRoute: typeof MeasurementGuideRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement-guide': {
      id: '/measurement-guide'
      path: '/measurement-guide'
      fullPath: '/measurement-guide'
      preLoaderRoute: typeof MeasurementGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric-guide': {
      id: '/fabric-guide'
      path: '/fabric-guide'
      fullPath: '/fabric-guide'
      preLoaderRoute: typeof FabricGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CollectionsRoute: CollectionsRoute,
  ConsultationRoute: ConsultationRoute,
  DesignRoute: DesignRoute,
  FabricGuideRoute: FabricGuideRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HowItWorksRoute: HowItWorksRoute,
  MeasurementGuideRoute: MeasurementGuideRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
